baseURL = "https://captus.github.io/"
languageCode = "en-us"
title = "Captus documentation"
theme = "hugo-theme-relearn"

[params]
editURL = "https://github.com/edgardomortiz/Captus/tree/master/docs/content/"
author = "Edgardo M. Ortiz"
description = "Documentation and tutorials for Captus"
showVisitedLinks = true
disableInlineCopyToClipBoard = true
disableBreadcrumb = false
disableNextPrev = false
themeVariant = "green"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
unsafe = true

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/edgardomortiz/Captus"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Credits"
url = "more/credits"
weight = 15