baseURL = "http://example.org/"
languageCode = "en-us"

title = "Captus documentation"
theme = "hugo-theme-relearn"
themesdir = "themes"

[params]
  editURL = "https://github.com/edgardomortiz/Captus/docs/content/"
  baseURL = "https://github.com/edgardomortiz/Captus/docs/"
  description = "Documentation and tutorials for Captus"
  author = "Edgardo M. Ortiz"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "green"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
  unsafe= true

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/edgardomortiz/Captus"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Credits"
url = "/credits"
weight = 15